### Q1.What are the different data structures used in Tensorflow?. Give some examples
#### Ans
The different data structures used in TensorFlow include tensors, variables, and constants. Tensors are multi-dimensional arrays that store and manipulate data. Variables are mutable tensors that persist across executions and are commonly used for model parameters. Constants are immutable tensors that hold fixed values.


#### Q2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an examplec
#### Ans
TensorFlow constants are used for storing fixed values that remain unchanged during computation. Once created, their values cannot be modified. For example, tf.constant(5) creates a constant tensor with a value of 5.

On the other hand, TensorFlow variables are mutable tensors that can be updated and modified during computation, making them suitable for storing and updating model parameters during training. For example, tf.Variable(0.0) creates a variable tensor with an initial value of 0.0 that can be updated using assignment operations.

#### Q3.Describe the process of matrix addition, multiplication, and elementDwise operations in TensorFlow. answer in brief really brief
#### Ans
Matrix addition, multiplication, and element-wise operations in TensorFlow are performed as follows:
* Matrix addition: It involves adding two matrices of the same shape element-wise. For example, tf.add(matrix1, matrix2) performs element-wise addition of matrix1 and matrix2.

* Matrix multiplication: It can be performed using the tf.matmul() function, which computes the matrix product of two tensors. For example, tf.matmul(matrix1, matrix2) calculates the matrix multiplication of matrix1 and matrix2.

* Element-wise operations: TensorFlow provides various element-wise operations such as element-wise addition (tf.add()), subtraction (tf.subtract()), multiplication (tf.multiply()), division (tf.divide()), exponentiation (tf.pow()), and more. These operations apply the operation element-wise to the corresponding elements of the input tensors.


#### Creating and Manipulating Matrices
1. Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the values of matrix A.
2. Create a Gaussian matrix B with dimensions x, using TensorFlow's truncated_normal function. Display the values of matrix B
3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a
mean of 2 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values
of matrix.
4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.
5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [7]:
import tensorflow as tf
A=tf.random.normal(shape=(2,2))
print(f'Matrix A is {A.numpy()}')

Matrix A is [[ 0.256417   -1.5889072 ]
 [-0.03304625 -1.907607  ]]


In [8]:
B=tf.random.truncated_normal(shape=(2,2))
print('Matrix B is ')
print(B.numpy())

Matrix B is 
[[-1.8049802  -0.36366284]
 [-1.0687172  -0.3276713 ]]


In [9]:
C=tf.random.normal(shape=(2,2),mean=2,stddev=0.5)
print('Matrix C is ')
print(C.numpy())

Matrix C is 
[[2.447211  1.7218874]
 [1.2911298 1.8322212]]


In [10]:
D=tf.add(A,B)
D

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.5485631, -1.9525701],
       [-1.1017635, -2.2352781]], dtype=float32)>

In [11]:
E = tf.matmul(C, D)
E

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-5.6867733, -8.627248 ],
       [-4.01807  , -6.616545 ]], dtype=float32)>

####  Performing Additional Matrix Operations
1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function.  
2. Calculate the transpose of matrix F and store the result in matrix G
3. Calculate the element D,wise exponential of matrix F and store the result in matrix.
4. Create a matrix I by concatenating matrix F and matrix G horizontally.
5. Create a matrix J by concatenating matrix F and matrix H vertically.

In [13]:
F=tf.random.uniform(shape=(2,2))
print(F.numpy(),'\n')
G=tf.transpose(F)
print(G.numpy(),'\n')
H=tf.exp(F)
print(H.numpy(),'\n')
I=tf.concat([F,H],axis=1) # storing the values norizontally
print(I.numpy(),'\n')
J=tf.concat([F,H],axis=0) # storing the values vertically
print(J.numpy(),'\n')

[[0.3373288  0.9951633 ]
 [0.7038157  0.02614999]] 

[[0.3373288  0.7038157 ]
 [0.9951633  0.02614999]] 

[[1.4011997 2.705166 ]
 [2.0214512 1.0264949]] 

[[0.3373288  0.9951633  1.4011997  2.705166  ]
 [0.7038157  0.02614999 2.0214512  1.0264949 ]] 

[[0.3373288  0.9951633 ]
 [0.7038157  0.02614999]
 [1.4011997  2.705166  ]
 [2.0214512  1.0264949 ]] 

